// packages/orchestrated/frontend-react/src/components/CustomerTable.jsx
import React from 'react';
import Button from './Button';
import { Table, Tbody, Td, Th, Thead, Tr } from './Table';
import { Working } from './Working';
import { useAuth } from './AuthProvider';

const isStructured = (value) =>
  value && typeof value === 'object' && typeof value.text === 'string';

const isForgotten = (value) =>
  isStructured(value) && value.forgotten === true;

const isRestricted = (value) =>
  isStructured(value) && value.restricted === true;

const isUnauthorized = (value) =>
  isStructured(value) && value.unauthorized === true;

const displayValue = (value) =>
  isStructured(value) ? value.text : value;

const CustomerTable = ({ data, rowEdit, onPlaceOrder, onForget }) => {
  const { roles, sub } = useAuth();
  const isAdmin = (roles || []).includes('admin');
  return data ? (
    <Table>
      <Thead>
        <Tr>
          <Th />
          <Th>Id</Th>
          <Th>Name</Th>
        </Tr>
      </Thead>
      <Tbody>
        {data.map((row) => {
          const forgotten = isForgotten(row.name);
          const restricted = isRestricted(row.name);
          const unauthorized = isUnauthorized(row.name);
          const unavailable = forgotten || restricted || unauthorized;
          const isOwner = row.id === sub;
          const canAct = isAdmin || isOwner;
          return (
            <Tr key={row.id}>
              <Td>
                {canAct && (
                  <>
                    <Button
                      kind="inline"
                      onClick={() => rowEdit(row.id)}
                      text="Edit"
                      disabled={unavailable}
                    />
                    <Button
                      kind="inline"
                      onClick={() => onPlaceOrder(row.id)}
                      text="Place Order"
                      disabled={unavailable}
                    />
                    {!unavailable && (
                      <Button
                        kind="inline"
                        onClick={() => onForget(row.id, row.name)}
                        text="Forget"
                      />
                    )}
                  </>
                )}
              </Td>
              <Td>{row.id}</Td>
              <Td>{displayValue(row.name)}</Td>
            </Tr>
          );
        })}
      </Tbody>
    </Table>
  ) : (
    <Working />
  );
};

export default React.memo(CustomerTable);

// packages/orchestrated/frontend-svelte/src/lib/CustomerTable.svelte
<script>
  import { v4 as uuid } from 'uuid';

  import Button from './Button.svelte';
  import { forgetSubject } from './commands';
  import { authState } from './auth';

  import Table from './table/Table.svelte';
  import Tbody from './table/Tbody.svelte';
  import Td from './table/Td.svelte';
  import Th from './table/Th.svelte';
  import Thead from './table/Thead.svelte';
  import Tr from './table/Tr.svelte';
  import Working from './Working.svelte';

  export let store;

  $: isAdmin = ($authState.roles || []).includes('admin');
  $: userSub = $authState.sub;

  const isStructured = (value) =>
    value && typeof value === 'object' && typeof value.text === 'string';

  const isForgotten = (value) =>
    isStructured(value) && value.forgotten === true;

  const isRestricted = (value) =>
    isStructured(value) && value.restricted === true;

  const isUnauthorized = (value) =>
    isStructured(value) && value.unauthorized === true;

  const displayValue = (value) =>
    isStructured(value) ? value.text : value;

  const handleForget = (id, name) => {
    const displayName = displayValue(name);
    if (confirm(`Forget customer "${displayName}"? This cannot be undone.`)) {
      forgetSubject(id);
    }
  };
</script>

{#if !$store.loaded}
  <Working />
{:else if $store.isEmpty}
  <div class="p-2 bg-yellow-200">No data</div>
{:else}
  <Table>
    <Thead>
      <Tr>
        <Th />
        <Th>Id</Th>
        <Th>Name</Th>
      </Tr>
    </Thead>
    <Tbody>
      {#each $store.data as row}
        {@const forgotten = isForgotten(row.name)}
        {@const restricted = isRestricted(row.name)}
        {@const unauthorized = isUnauthorized(row.name)}
        {@const unavailable = forgotten || restricted || unauthorized}
        {@const isOwner = row.id === userSub}
        {@const canAct = isAdmin || isOwner}
        <Tr>
          <Td>
            {#if canAct}
              <Button
                kind="inline"
                text="Edit"
                target={unavailable ? null : `/customer/${row.id}`}
                disabled={unavailable}
              />
              <Button
                kind="inline"
                text="Place Order"
                target={unavailable ? null : `/order/${row.id}/${uuid()}`}
                disabled={unavailable}
              />
              {#if !unavailable}
                <Button
                  kind="inline"
                  text="Forget"
                  on:click={() => handleForget(row.id, row.name)}
                />
              {/if}
            {/if}
          </Td>
          <Td>{row.id}</Td>
          <Td>{displayValue(row.name)}</Td>
        </Tr>
      {/each}
    </Tbody>
  </Table>
{/if}
