// packages/orchestrated/frontend-react/src/components/OrderTable.jsx
import React from 'react';
import { Table, Tbody, Td, Th, Thead, Tr } from './Table';
import { Working } from './Working';

const displayValue = (value) =>
  value && typeof value === 'object' && value.forgotten === true
    ? value.text
    : value;

const OrderTable = ({ data }) => {
  return data ? (
    <Table>
      <Thead>
        <Tr>
          <Th>Id</Th>
          <Th>Text</Th>
          <Th>Value</Th>
          <Th>Customer</Th>
          <Th>Status</Th>
          <Th>USD Info</Th>
        </Tr>
      </Thead>
      <Tbody>
        {data.map((row) => (
          <Tr key={row.id} warn={row.status !== 'confirmed'}>
            <Td>{row.id}</Td>
            <Td>{row.text}</Td>
            <Td>{row.value}</Td>
            <Td>{displayValue(row.customerName)}</Td>
            <Td warn={row.status !== 'confirmed'}>{row.status}</Td>
            <Td>{JSON.stringify(row.usdInfo, null, 2)}</Td>
          </Tr>
        ))}
      </Tbody>
    </Table>
  ) : (
    <Working />
  );
};

export default React.memo(OrderTable);

// packages/orchestrated/frontend-svelte/src/lib/OrderTable.svelte
<script>
  import Table from './table/Table.svelte';
  import Tbody from './table/Tbody.svelte';
  import Td from './table/Td.svelte';
  import Th from './table/Th.svelte';
  import Thead from './table/Thead.svelte';
  import Tr from './table/Tr.svelte';
  import Working from './Working.svelte';

  export let store;

  const displayValue = (value) =>
    value && typeof value === 'object' && value.forgotten === true
      ? value.text
      : value;
</script>

{#if !$store.loaded}
  <Working />
{:else if $store.isEmpty}
  <div class="p-2 bg-yellow-200">No data</div>
{:else}
  <Table>
    <Thead>
      <Tr>
        <Th>Id</Th>
        <Th>Text</Th>
        <Th>Value</Th>
        <Th>Customer</Th>
        <Th>Status</Th>
        <Th>USD Info</Th>
      </Tr>
    </Thead>
    <Tbody>
      {#each $store.data as row}
        <Tr  warn={row.status !== 'confirmed'}>
          <Td>{row.id}</Td>
          <Td>{row.text}</Td>
          <Td>{row.value}</Td>
          <Td>{displayValue(row.customerName)}</Td>
          <Td warn={row.status !== 'confirmed'}>{row.status}</Td>
          <Td>{JSON.stringify(row.usdInfo, null, 2)}</Td>
        </Tr>
      {/each}
    </Tbody>
  </Table>
{/if}
