// packages/llm-demo/frontend/src/lib/CustomerTable.svelte
<script>
  import { nanoid } from 'nanoid';

  import Button from './Button.svelte';
  import { requestExplain } from './contextDataStore.js';

  import Table from './table/Table.svelte';
  import Tbody from './table/Tbody.svelte';
  import Td from './table/Td.svelte';
  import Th from './table/Th.svelte';
  import Thead from './table/Thead.svelte';
  import Tr from './table/Tr.svelte';
  import Working from './Working.svelte';

  export let store;
</script>

{#if !$store.loaded}
  <Working />
{:else if $store.isEmpty}
  <div class="p-2 bg-yellow-200">No data</div>
{:else}
  <Table>
    <Thead>
      <Tr>
        <Th />
        <Th>Id</Th>
        <Th>Name</Th>
      </Tr>
    </Thead>
    <Tbody>
      {#each $store.data as row}
        <Tr>
          <Td>
            <Button kind="inline" text="Edit" target={`/customer/${row.id}`} />
            <Button
              kind="inline"
              text="Place Order"
              target={`/order/${row.id}/${nanoid()}`}
            />
            <button
              class="text-xs text-blue-600 hover:underline"
              on:click={() => requestExplain(row.id, 'customer', row.name)}
            >Explain</button>
          </Td>
          <Td>{row.id}</Td>
          <Td>{row.name}</Td>
        </Tr>
      {/each}
    </Tbody>
  </Table>
{/if}

// packages/orchestrated/frontend-react/src/components/CustomerTable.jsx
import React from 'react';
import Button from './Button';
import { Table, Tbody, Td, Th, Thead, Tr } from './Table';
import { Working } from './Working';

const CustomerTable = ({ data, rowEdit, onPlaceOrder, onForget }) => {
  return data ? (
    <Table>
      <Thead>
        <Tr>
          <Th />
          <Th>Id</Th>
          <Th>Name</Th>
        </Tr>
      </Thead>
      <Tbody>
        {data.map(row => (
          <Tr key={row.id}>
            <Td>
              <Button
                kind="inline"
                onClick={() => rowEdit(row.id)}
                text="Edit"
              />
              <Button
                kind="inline"
                onClick={() => onPlaceOrder(row.id)}
                text="Place Order"
              />
              <Button
                kind="inline"
                onClick={() => onForget(row.id, row.name)}
                text="Forget"
              />
            </Td>
            <Td>{row.id}</Td>
            <Td>{row.name}</Td>
          </Tr>
        ))}
      </Tbody>
    </Table>
  ) : (
    <Working />
  );
};

export default React.memo(CustomerTable);
